name: CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  image-build:
    name: Image build
    uses: hajle-silesia/.github/.github/workflows/shared-image-build.yaml@v2.5.0
    with:
      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
      docker-hub-namespace: ${{ vars.DOCKER_HUB_NAMESPACE }}
      dir: image
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
